-- MySQL Script generated by MySQL Workbench
-- Tue Jan 10 12:09:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema barterplus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barterplus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barterplus` DEFAULT CHARACTER SET utf8 ;
USE `barterplus` ;

-- -----------------------------------------------------
-- Table `barterplus`.`participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barterplus`.`participants` (
  `uuid` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `age` INT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barterplus`.`barterGame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barterplus`.`barterGame` (
  `num` INT NOT NULL,
  `duration` INT NULL,
  `winner` INT NULL,
  PRIMARY KEY (`num`),
  INDEX `winn_idx` (`winner` ASC) VISIBLE,
  CONSTRAINT `winn`
    FOREIGN KEY (`winner`)
    REFERENCES `barterplus`.`participants` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barterplus`.`TradeRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barterplus`.`TradeRequest` (
  `RequestID` INT NOT NULL,
  `requester` INT NOT NULL,
  `requested` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `timeCreated` DOUBLE NULL,
  `timeFinished` DOUBLE NULL,
  `game` INT NULL,
  PRIMARY KEY (`RequestID`),
  INDEX `request_idx` (`requester` ASC, `requested` ASC) VISIBLE,
  INDEX `barterG_idx` (`game` ASC) VISIBLE,
  CONSTRAINT `players`
    FOREIGN KEY (`requester` , `requested`)
    REFERENCES `barterplus`.`participants` (`uuid` , `uuid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `barterG`
    FOREIGN KEY (`game`)
    REFERENCES `barterplus`.`barterGame` (`num`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barterplus`.`Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barterplus`.`Materials` (
  `Namespace` VARCHAR(30) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`Namespace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barterplus`.`Trade_has_Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barterplus`.`Trade_has_Materials` (
  `TradeRequest_RequestID` INT NOT NULL,
  `Materials_Namespace` VARCHAR(30) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`TradeRequest_RequestID`, `Materials_Namespace`),
  INDEX `fk_Trade_has_Materials_Materials1_idx` (`Materials_Namespace` ASC) VISIBLE,
  INDEX `fk_Trade_has_Materials_TradeRequest1_idx` (`TradeRequest_RequestID` ASC) VISIBLE,
  CONSTRAINT `fk_Trade_has_Materials_Materials1`
    FOREIGN KEY (`Materials_Namespace`)
    REFERENCES `barterplus`.`Materials` (`Namespace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trade_has_Materials_TradeRequest1`
    FOREIGN KEY (`TradeRequest_RequestID`)
    REFERENCES `barterplus`.`TradeRequest` (`RequestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barterplus`.`profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barterplus`.`profession` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barterplus`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barterplus`.`players` (
  `players_uuid` INT NOT NULL,
  `barterGame_num` INT NOT NULL,
  `profession` INT NULL,
  PRIMARY KEY (`players_uuid`, `barterGame_num`),
  INDEX `fk_players_has_barterGame_barterGame1_idx` (`barterGame_num` ASC) VISIBLE,
  INDEX `fk_players_has_barterGame_players1_idx` (`players_uuid` ASC) VISIBLE,
  INDEX `prof_idx` (`profession` ASC) VISIBLE,
  CONSTRAINT `fk_players_has_barterGame_players1`
    FOREIGN KEY (`players_uuid`)
    REFERENCES `barterplus`.`participants` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_has_barterGame_barterGame1`
    FOREIGN KEY (`barterGame_num`)
    REFERENCES `barterplus`.`barterGame` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prof`
    FOREIGN KEY (`profession`)
    REFERENCES `barterplus`.`profession` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
